### ISSUE TITLE
Reporte_de_Practica_2_Equipo_Mana

### ISSUE THREAD

**Issue by JeroRoque** [SistemasTecTlaxiaco/actividad-2-entrevista-equipo-evelin#1]
[Reporte_de_Practica_2_Equipo_Mana.pdf](https://github.com/SistemasTecTlaxiaco/actividad-2-entrevista-equipo-evelin/files/12581791/Reporte_de_Practica_2_Equipo_Mana.pdf)

**Comment by Arlet04** [comment]
Preparacion 4
Conocimiento ganado 4
Informe 3
Redaccion 3
Calificación 14
Por indicaciones del docente favor de adjuntar sus evidencias ya sea audio, video, etc de la entrevista

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
